### ISSUE TITLE
Cannot make new folder, upload allowed

### ISSUE THREAD

**Issue by Ad-Man-Gamer** [NaitLee/PHFS#3]
When trying to make a new folder in the web interface for a directory that is in the upload_allowed_paths, the following error occurs in the browser.

`~lib.js:156 Uncaught TypeError: Cannot read property 'focus' of null`
`~lib.js:99 POST http://localhost:8090/uploads/?mode=section&id=ajax.mkdir 404 (NOT FOUND)`

I'm guessing this is not meant to happen?

**Comment by NaitLee** [comment]
Technology explained, in HFS, "make new folder" is not a part of "upload" feature.

When click on "New Folder", what happened is:

- Browser makes an ajax POST request to server, with folder name as parameter in post body
- In HFS, this request calls the "ajax.mkdir" section (in template), and HFS makes new folder according to the request info

Since this project is WIP, the "mode=section" is not implemented yet, and making folder will fail.

If you want anything to be implemented with high priority, just say, I will do it 😃

Thanks for contribution! 🎉

**Comment by NaitLee** [comment]
[This commit](https://github.com/NaitLee/PHFS/commit/69fb99205a65d74ca1ae8e914df1738bf7b4e0b5) solved this issue, so it can be closed now ;)
